@extends('layouts.app')
@section('title', 'Central Hospital Indore | Care Beyond the Ordinary')
@section('meta_description', 'A more personal vision for healthcare in Indore. Discover Central Hospital, meet our specialists and plan your visit.')
@section('content')
<section class="at-hero at-signature-hero" aria-labelledby="hero-title">
 <div class="at-hero-stage">
  <div class="at-arrival-stage"><figure class="at-arrival"><img src="{{ asset('images/hospital/reception-preview.webp') }}" width="1672" height="941" fetchpriority="high" alt="AI completion preview based on the actual Central Hospital reception"></figure></div>
  <div class="at-hero-veil" aria-hidden="true"></div><div class="at-image-caption"><span>A warmer welcome.<br><em>A different feeling.</em></span><small>AI COMPLETION PREVIEW</small></div>
  <div class="at-wrap at-hero-heading"><div class="at-hero-title-block"><span class="at-eyebrow"><i></i> CARE WITH COMPASSION</span><h1 id="hero-title"><span>Exceptional care.</span><br><em>Entirely personal.</em></h1><p class="at-hero-intro">Expertise you can trust.<br>A welcome you can feel.</p><div class="at-hero-actions"><a class="at-pill at-pill-light" href="{{ route('about') }}">Discover Central Hospital <span aria-hidden="true">↗</span></a><a class="at-hero-doctors" href="{{ route('doctors') }}">Meet our doctors ↗</a></div></div></div>
  <div class="at-wrap at-hero-foot"><span><i></i> INDORE · A NEW HOME FOR CARE</span><a href="{{ route('contact') }}">Open 24 hours | Contact our team ↗</a></div>
 </div>
</section>
<section id="our-philosophy" class="at-philosophy">
 <div class="at-wrap at-philosophy-grid"><div class="at-sculpture"><canvas id="care-sculpture" aria-label="Interactive three dimensional flowing sculpture symbolising connected care" role="img"></canvas><span class="at-sculpture-caption">CONNECTED BY CARE</span><button type="button" id="sculpture-motion" aria-pressed="false" aria-label="Pause sculpture animation">Pause motion <span aria-hidden="true">Ⅱ</span></button></div><div class="at-philosophy-copy"><span class="at-eyebrow">THE WAY WE SEE CARE</span><h2 data-word-reveal>Not just feeling better.<br>Feeling like <em>yourself again.</em></h2><p>Life is in the little things. Our vision is to help you get back to yours—with expertise, understanding, and time for what matters.</p><a class="at-link at-link-light" href="{{ route('about') }}">Get to know us <span aria-hidden="true">↗</span></a></div></div>
</section>
<section class="at-life at-section" id="discover-care"><div class="at-wrap at-life-grid">
 <div class="at-life-copy"><span class="at-eyebrow">FOR THE LIFE YOU LOVE</span><h2>Small moments.<br><em>Everything</em><br>to live for.</h2><p>For growing families. For new beginnings.<br>For getting back to doing what you love.</p><a class="at-pill" href="{{ route('services') }}">Explore our expertise <span aria-hidden="true">↗</span></a></div>
 <figure class="at-family"><img src="{{ asset('images/atelier/family-editorial.webp') }}" width="1536" height="1024" loading="lazy" alt="Illustrative image of a mother and daughter sharing a quiet, happy moment"><figcaption>MORE LIFE IN EVERY MOMENT</figcaption><span class="at-family-stamp" aria-hidden="true">A little<br>more <em>life.</em></span></figure>
</div></section>
<section class="at-expertise at-section"><div class="at-wrap"><div class="at-section-heading"><div><span class="at-eyebrow">SPECIALIST CARE. PERSONAL ATTENTION.</span><h2>In exceptionally<br><em>good hands.</em></h2></div><p>Expertise for different needs.<br>One shared commitment to you.</p></div>
 <div class="at-expertise-list">
 @foreach([['Women’s health','Gynaecology, fertility & fetal medicine','Care through the changes, milestones and new beginnings in your life.','M12 21s-9-5.5-9-12a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 6.5-9 12-9 12Z'],['Children & newborns','Paediatrics & neonatology','A thoughtful, reassuring approach to the smallest members of your family.','M5 20c0-8 14-8 14 0M8 8a4 4 0 1 0 8 0 4 4 0 0 0-8 0'],['Bones & movement','Orthopaedics & joint care','Support for moving more comfortably and returning to the things you enjoy.','M8 4a3 3 0 1 0-4 4l12 12a3 3 0 1 0 4-4Z'],['Specialist medicine','Connected medical expertise','The right conversations, clear guidance and a considered next step.','M2 12h5l3-8 4 16 3-8h5']] as [$name,$speciality,$description,$path])
 <details class="at-speciality" @if($loop->first) open @endif><summary><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.1" aria-hidden="true"><path d="{{ $path }}"/></svg><h3>{{ $name }}</h3><span class="at-speciality-sub">{{ $speciality }}</span><span class="at-plus" aria-hidden="true">+</span></summary><div class="at-speciality-detail"><p>{{ $description }}</p><a class="at-link" href="{{ route('services') }}">Discover this speciality ↗</a></div></details>
 @endforeach
 </div>
</div></section>
<section class="at-journey" aria-labelledby="spaces-title"><div class="at-journey-sticky"><div class="at-wrap at-section-heading"><div><span class="at-eyebrow">A SENSE OF PLACE</span><h2 id="spaces-title">Room to <em>feel better.</em></h2></div><div class="at-gallery-controls"><button type="button" data-gallery-step="-1" aria-label="Previous hospital concept">←</button><button type="button" data-gallery-step="1" aria-label="Next hospital concept">→</button></div></div><div class="at-gallery-window"><div class="at-gallery-track">
 <figure class="at-space-card"><img src="{{ asset('images/hospital/reception-preview.webp') }}" width="1672" height="941" loading="lazy" alt="AI completion preview of the actual wood-and-white hospital reception"><figcaption><h3>A calmer arrival.</h3><span>Space to pause. People to guide you.</span></figcaption><small>AI COMPLETION PREVIEW</small></figure>
 <figure class="at-space-card"><img src="{{ asset('images/atelier/recovery-concept.webp') }}" width="1536" height="1024" loading="lazy" alt="Illustrative private recovery suite concept with natural light and a visitor chair"><figcaption><h3>A little more comfort.</h3><span>Our vision for thoughtful recovery spaces.</span></figcaption><small>INTERIOR CONCEPT</small></figure>
 <figure class="at-space-card"><img src="{{ asset('images/hospital/exterior-preview.webp') }}" width="1672" height="941" loading="lazy" alt="AI completion preview based on the actual blue-glass Central Hospital building"><figcaption><h3>A new chapter for Indore.</h3><span>A place for our vision to take shape.</span></figcaption><small>AI COMPLETION PREVIEW</small></figure>
 </div></div><div class="at-wrap at-gallery-bottom"><span>Reception and exterior previews are AI-enhanced from site photos; the recovery room is an illustrative concept.</span><a class="at-link" href="{{ route('gallery') }}">View the gallery ↗</a></div></div></section>
<section class="at-breathe" aria-labelledby="breathe-title">
 <div class="at-breathe-scene">
  <img src="{{ asset('images/atelier/recovery-concept.webp') }}" width="1536" height="1024" loading="lazy" alt="Interior concept of a quiet recovery room overlooking a leafy garden">
  <div class="at-breathe-shade"></div><div class="at-breathe-shutter at-breathe-shutter-left" aria-hidden="true"></div><div class="at-breathe-shutter at-breathe-shutter-right" aria-hidden="true"></div>
  <div class="at-breathe-copy"><span class="at-eyebrow">ROOM FOR WHAT MATTERS</span><h2 id="breathe-title">A little space.<br>To feel <em>like you.</em></h2><a class="at-link at-link-light" href="{{ route('about') }}">Discover our approach ↗</a></div>
  <span class="at-breathe-note">INTERIOR CONCEPT</span>
 </div>
</section>
<section id="care-team" class="at-doctors at-section"><div class="at-wrap"><div class="at-section-heading"><div><span class="at-eyebrow">THE PEOPLE BEHIND THE PROMISE</span><h2>Specialists in medicine.<br><em>People at heart.</em></h2></div><a class="at-link" href="{{ route('doctors') }}">Meet the team ↗</a></div><div class="at-doctor-grid">
@foreach($doctors->take(2) as $doctor)
<a class="at-doctor" href="{{ route('doctor.profile', $doctor) }}"><div class="at-doctor-image">@if($doctor->photo)<img src="{{ asset($doctor->photo) }}" width="600" height="700" alt="{{ $doctor->name }}" loading="lazy">@else<span class="at-monogram">{{ mb_substr(str_replace('Dr. ', '', $doctor->name),0,1) }}</span>@endif<span class="at-doctor-more">Meet your doctor ↗</span></div><h3>{{ $doctor->name }}</h3><p>{{ $doctor->designation }}</p></a>
@endforeach
</div></div></section>
<section class="at-conversation"><div class="at-wrap at-conversation-grid"><span class="at-big-quote" aria-hidden="true">“</span><div><span class="at-eyebrow">OUR PROMISE TO YOU</span><h2 data-word-reveal>We believe being heard<br>is where <em>healing begins.</em></h2><p>Time for your questions. Clarity about your choices.<br> Care that remembers the person behind the patient.</p><a class="at-link" href="{{ route('contact') }}">Start a conversation ↗</a></div></div></section>
<section class="at-considered at-section" aria-labelledby="considered-title"><div class="at-wrap at-considered-grid">
 <div class="at-considered-intro"><span class="at-eyebrow">EVERY STEP, CONSIDERED</span><h2 id="considered-title">At your pace.<br><em>By your side.</em></h2><p>A question. A conversation. A clearer next step.</p><a class="at-link" href="{{ route('contact') }}">Talk to our team ↗</a></div>
 <div class="at-considered-cards">
  <article class="at-considered-card"><span class="at-card-symbol" aria-hidden="true">↗</span><span class="at-eyebrow">A CONVERSATION FIRST</span><h3>Start with<br>what’s on your mind.</h3><p>Ask about the hospital, our specialists or available services. We’ll help you find your starting point.</p><a class="at-link" href="{{ route('contact') }}">Get in touch ↗</a><span class="at-card-art at-card-art-circle" aria-hidden="true"></span></article>
  <article class="at-considered-card"><span class="at-card-symbol" aria-hidden="true">✳</span><span class="at-eyebrow">A PERSONAL CONNECTION</span><h3>Find the person.<br>Behind the expertise.</h3><p>Meet our doctors and explore their areas of care before making your next move.</p><a class="at-link" href="{{ route('doctors') }}">Meet our specialists ↗</a><span class="at-card-art at-card-art-arch" aria-hidden="true"></span></article>
  <article class="at-considered-card"><span class="at-card-symbol" aria-hidden="true">⌁</span><span class="at-eyebrow">A NEW CHAPTER, TOGETHER</span><h3>Stay connected.<br>To your care.</h3><p>Connect with our team for appointments and service availability.</p><a class="at-link" href="{{ route('contact') }}">Stay connected ↗</a><span class="at-card-art at-card-art-lines" aria-hidden="true"></span></article>
 </div>
</div></section>
@if($testimonials->isNotEmpty())
<section class="at-stories at-section"><div class="at-wrap"><div class="at-section-heading"><div><span class="at-eyebrow">IN THEIR OWN WORDS</span><h2>Care that <em>stays with you.</em></h2></div><a class="at-link" href="{{ route('patient-stories') }}">All patient stories ↗</a></div><div class="at-story-grid">@foreach($testimonials->take(2) as $story)<article><blockquote>{{ \Illuminate\Support\Str::limit($story->content,240) }}</blockquote><p><span>{{ mb_substr($story->client_name,0,1) }}</span>{{ $story->client_name }}</p></article>@endforeach</div></div></section>
@endif
<section class="at-invitation"><div class="at-wrap"><span class="at-eyebrow">CENTRAL HOSPITAL INDORE</span><h2>Your health.<br><em>Our whole heart.</em></h2><div class="at-invitation-actions"><a class="at-pill at-pill-light" href="{{ route('contact') }}">Let’s connect <span>↗</span></a><a href="tel:{{ $siteSettings->phone_href }}">{{ $siteSettings->phone_display }}</a></div><div class="at-opening"><span><i></i> OPEN 24 HOURS</span><p>Contact our team for appointments and service availability.</p></div></div><span class="at-invitation-outline" aria-hidden="true">Care.</span></section>
@endsection
